name: liquid-monadic-selectionsort
version: 0.1.0.0
github: "githubuser/liquid-monadic-selectionsort"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Please see the README on GitHub at
  <https://github.com/githubuser/liquid-monadic-selectionsort#readme>

dependencies:
  - liquidhaskell == 0.8.10.7
  - liquid-base == 4.15.0.0

library:
  source-dirs: src
  default-extensions:
    - GADTs
    - KindSignatures
    - ExplicitForAll
    - RankNTypes
    - FlexibleInstances
    - UndecidableInstances
    - MultiParamTypeClasses
  ghc-options:
    - -fplugin=LiquidHaskell
#
# executables:
#   liquid-monadic-selectionsort-exe:
#     main: Main.hs
#     source-dirs: app
#     ghc-options:
#       - -threaded
#       - -rtsopts
#       - -with-rtsopts=-N
#     dependencies:
#       - liquid-monadic-selectionsort

# tests:
#   liquid-monadic-selectionsort-test:
#     main: Spec.hs
#     source-dirs: test
#     default-extensions:
#       - GADTs
#       - KindSignatures
#       - ExplicitForAll
#       - RankNTypes
#       - FlexibleInstances
#       - UndecidableInstances
#       - MultiParamTypeClasses
#     ghc-options:
#       - -fplugin=LiquidHaskell
#       - -fplugin-opt=LiquidHaskell:--reflection
#       - -fplugin-opt=LiquidHaskell:--ple-local
#       - -fplugin-opt=LiquidHaskell:--diff
#       - -fplugin-opt=LiquidHaskell:--short-names
#       - -fplugin-opt=LiquidHaskell:--prune-unsorted
#     dependencies:
#       - liquid-monadic-selectionsort
